AllCops:
  TargetRubyVersion: 2.1

Style/IndentationConsistency:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/LineLength:
  Max: 190

Style/HashSyntax:
  EnforcedStyle: ruby19

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
